version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - checkout
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Build
          command: ./gradlew build
workflows:
  version: 2
  build:
    jobs:
      - build